// Auto-generated product data from price lists
// Prices are in PKR (Pakistani Rupees)
const productsData = [
    {
        id: 1,
        name: 'HASSAN IRFAN 1947 THE GREEN',
        category: 'men',
        type: 'FRENCH',
        price: 1947,
        image: '🌸',
        format: 'spray',
        brand: 'HASSAN IRFAN',
        sizes: {
            '5ML': 1947,
            '15ML': 752,
            '30ML': 2912,
            '50ML': 4788,
            '100ML': 6817,
        }
    },
    {
        id: 2,
        name: 'HASSAN IRFAN AQUAMARINE***',
        category: 'men',
        type: 'FRENCH',
        price: 457,
        image: '🌸',
        format: 'spray',
        brand: 'HASSAN IRFAN',
        sizes: {
            '5ML': 457,
            '15ML': 1337,
            '30ML': 3016,
            '50ML': 3862,
            '100ML': 6180,
        }
    },
    {
        id: 3,
        name: 'HASSAN IRFAN ARADH AL DUBAI          (NEW)',
        category: 'men',
        type: 'ARABIC',
        price: 708,
        image: '🌸',
        format: 'spray',
        brand: 'HASSAN IRFAN',
        sizes: {
            '5ML': 708,
            '15ML': 1241,
            '30ML': 2908,
            '50ML': 4297,
            '100ML': 6874,
        }
    },
    {
        id: 4,
        name: 'HASSAN IRFAN ASHES OF ROSE (FLAGSHIP)***',
        category: 'unisex',
        type: 'ORIENTAL',
        price: 1084,
        image: '🌸',
        format: 'spray',
        brand: 'HASSAN IRFAN',
        sizes: {
            '5ML': 1084,
            '15ML': 2445,
            '30ML': 4263,
            '50ML': 6930,
            '100ML': 11089,
        }
    },
    {
        id: 5,
        name: 'HASSAN IRFAN BERGAROSE',
        category: 'unisex',
        type: 'FLORAL',
        price: 781,
        image: '🌸',
        format: 'spray',
        brand: 'HASSAN IRFAN',
        sizes: {
            '5ML': 781,
            '15ML': 3069,
            '30ML': 4964,
            '50ML': 7109,
            '100ML': 11375,
        }
    },
    {
        id: 6,
        name: 'HASSAN IRFAN BEYOND VIOLET (FLAGSHIP)**',
        category: 'men',
        type: 'FRENCH',
        price: 503,
        image: '🌸',
        format: 'spray',
        brand: 'HASSAN IRFAN',
        sizes: {
            '5ML': 503,
            '15ML': 1586,
            '30ML': 3296,
            '50ML': 4330,
            '100ML': 6928,
        }
    },
    {
        id: 7,
        name: 'HASSAN IRFAN CANNABIS ONE',
        category: 'unisex',
        type: 'FRENCH',
        price: 470,
        image: '🌸',
        format: 'spray',
        brand: 'HASSAN IRFAN',
        sizes: {
            '5ML': 470,
            '15ML': 1409,
            '30ML': 3097,
            '50ML': 3998,
            '100ML': 6397,
        }
    },
    {
        id: 8,
        name: 'HASSAN IRFAN CHARGED HOMME',
        category: 'men',
        type: 'FRENCH',
        price: 494,
        image: '🌸',
        format: 'spray',
        brand: 'HASSAN IRFAN',
        sizes: {
            '5ML': 494,
            '15ML': 1535,
            '30ML': 3239,
            '50ML': 4235,
            '100ML': 6776,
        }
    },
    {
        id: 9,
        name: 'HASSAN IRFAN DAUNTLESS',
        category: 'men',
        type: 'FRENCH',
        price: 461,
        image: '🌸',
        format: 'spray',
        brand: 'HASSAN IRFAN',
        sizes: {
            '5ML': 461,
            '15ML': 1359,
            '30ML': 3040,
            '50ML': 3903,
            '100ML': 6246,
        }
    },
    {
        id: 10,
        name: 'HASSAN IRFAN ESSCENSE OF KHALEEJ',
        category: 'men',
        type: 'ARABIC',
        price: 508,
        image: '🌸',
        format: 'spray',
        brand: 'HASSAN IRFAN',
        sizes: {
            '5ML': 508,
            '15ML': 1611,
            '30ML': 3325,
            '50ML': 4377,
            '100ML': 7003,
        }
    },
    {
        id: 11,
        name: 'HASSAN IRFAN FLOWER OF NILE',
        category: 'women',
        type: 'FRENCH',
        price: 447,
        image: '🌸',
        format: 'spray',
        brand: 'HASSAN IRFAN',
        sizes: {
            '5ML': 447,
            '15ML': 1283,
            '30ML': 2955,
            '50ML': 3761,
            '100ML': 6018,
        }
    },
    {
        id: 12,
        name: 'HASSAN IRFAN FEMMENIGHT',
        category: 'women',
        type: 'FRENCH',
        price: 536,
        image: '🌸',
        format: 'spray',
        brand: 'HASSAN IRFAN',
        sizes: {
            '5ML': 536,
            '15ML': 1758,
            '30ML': 3490,
            '50ML': 4652,
            '100ML': 7443,
        }
    },
    {
        id: 13,
        name: 'HASSAN IRFAN HALLUCINATION***',
        category: 'unisex',
        type: 'UNIQUE',
        price: 968,
        image: '🌸',
        format: 'spray',
        brand: 'HASSAN IRFAN',
        sizes: {
            '5ML': 968,
            '15ML': 4062,
            '30ML': 6082,
            '50ML': 8972,
            '100ML': 14355,
        }
    },
    {
        id: 14,
        name: 'HASSAN IRFAN HEAVENLY APPLE**',
        category: 'women',
        type: 'FRENCH',
        price: 442,
        image: '🌸',
        format: 'spray',
        brand: 'HASSAN IRFAN',
        sizes: {
            '5ML': 442,
            '15ML': 1258,
            '30ML': 2927,
            '50ML': 3714,
            '100ML': 5942,
        }
    },
    {
        id: 15,
        name: 'HASSAN IRFAN METALLIC VETIVER**',
        category: 'unisex',
        type: 'FRENCH',
        price: 778,
        image: '🌸',
        format: 'spray',
        brand: 'HASSAN IRFAN',
        sizes: {
            '5ML': 778,
            '15ML': 3051,
            '30ML': 4945,
            '50ML': 7077,
            '100ML': 11323,
        }
    },
    {
        id: 16,
        name: 'HASSAN IRFAN MUKHALLAT YANGI',
        category: 'men',
        type: 'ARABIC',
        price: 548,
        image: '🌸',
        format: 'spray',
        brand: 'HASSAN IRFAN',
        sizes: {
            '5ML': 548,
            '15ML': 1823,
            '30ML': 3563,
            '50ML': 4775,
            '100ML': 7640,
        }
    },
    {
        id: 17,
        name: 'HASSAN IRFAN MUSKU FATI         (NEW)',
        category: 'unisex',
        type: 'ARABIC',
        price: 653,
        image: '🌸',
        format: 'spray',
        brand: 'HASSAN IRFAN',
        sizes: {
            '5ML': 653,
            '15ML': 2382,
            '30ML': 4192,
            '50ML': 5822,
            '100ML': 9315,
        }
    },
    {
        id: 18,
        name: 'HASSAN IRFAN MYSTERY MEN',
        category: 'men',
        type: 'FRENCH',
        price: 1055,
        image: '🌸',
        format: 'spray',
        brand: 'HASSAN IRFAN',
        sizes: {
            '5ML': 1055,
            '15ML': 4529,
            '30ML': 6607,
            '50ML': 9848,
            '100ML': 15757,
        }
    },
    {
        id: 19,
        name: 'HASSAN IRFAN 1 NAUTICAL MILE',
        category: 'men',
        type: 'FRENCH',
        price: 579,
        image: '🌸',
        format: 'spray',
        brand: 'HASSAN IRFAN',
        sizes: {
            '5ML': 579,
            '15ML': 1990,
            '30ML': 3751,
            '50ML': 5088,
            '100ML': 8140,
        }
    },
    {
        id: 20,
        name: 'HASSAN IRFAN NUTMEG TOBACCO',
        category: 'men',
        type: 'ORIENTAL',
        price: 485,
        image: '🌸',
        format: 'spray',
        brand: 'HASSAN IRFAN',
        sizes: {
            '5ML': 485,
            '15ML': 1487,
            '30ML': 3185,
            '50ML': 4145,
            '100ML': 6632,
        }
    },
    {
        id: 21,
        name: 'HASSAN IRFAN BLACK PLATINUM',
        category: 'men',
        type: 'FRENCH',
        price: 518,
        image: '🌸',
        format: 'spray',
        brand: 'HASSAN IRFAN',
        sizes: {
            '5ML': 518,
            '15ML': 1662,
            '30ML': 3412,
            '50ML': 3702,
            '100ML': 5223,
        }
    },
    {
        id: 22,
        name: 'HASSAN IRFAN PINKNADE',
        category: 'women',
        type: 'FRENCH',
        price: 458,
        image: '🌸',
        format: 'spray',
        brand: 'HASSAN IRFAN',
        sizes: {
            '5ML': 458,
            '15ML': 1346,
            '30ML': 3026,
            '50ML': 3880,
            '100ML': 6208,
        }
    },
    {
        id: 23,
        name: 'HASSAN IRFAN PATCHOULI & PEPPER for MEN',
        category: 'unisex',
        type: 'FRENCH',
        price: 423,
        image: '🌸',
        format: 'spray',
        brand: 'HASSAN IRFAN',
        sizes: {
            '5ML': 423,
            '15ML': 1157,
            '30ML': 2813,
            '50ML': 3525,
            '100ML': 5639,
        }
    },
    {
        id: 24,
        name: 'HASSAN IRFAN PASSION BLEND NO.27',
        category: 'unisex',
        type: 'FRENCH',
        price: 570,
        image: '🌸',
        format: 'spray',
        brand: 'HASSAN IRFAN',
        sizes: {
            '5ML': 570,
            '15ML': 1940,
            '30ML': 3694,
            '50ML': 4993,
            '100ML': 7989,
        }
    },
    {
        id: 25,
        name: 'HASSAN IRFAN ROGUE LEATHER',
        category: 'men',
        type: 'FRENCH',
        price: 533,
        image: '🌸',
        format: 'spray',
        brand: 'HASSAN IRFAN',
        sizes: {
            '5ML': 533,
            '15ML': 1745,
            '30ML': 3475,
            '50ML': 4628,
            '100ML': 7405,
        }
    },
    {
        id: 26,
        name: 'HASSAN IRFAN SAPHIRE BLUE',
        category: 'unisex',
        type: 'FRENCH',
        price: 477,
        image: '🌸',
        format: 'spray',
        brand: 'HASSAN IRFAN',
        sizes: {
            '5ML': 477,
            '15ML': 1447,
            '30ML': 3140,
            '50ML': 4069,
            '100ML': 6511,
        }
    },
    {
        id: 27,
        name: 'HASSAN IRFAN SMOKEY CANNABIS',
        category: 'unisex',
        type: 'FRENCH',
        price: 522,
        image: '🌸',
        format: 'spray',
        brand: 'HASSAN IRFAN',
        sizes: {
            '5ML': 522,
            '15ML': 1687,
            '30ML': 3410,
            '50ML': 4519,
            '100ML': 7231,
        }
    },
    {
        id: 28,
        name: 'HASSAN IRFAN SPICY FEMME (GEL FORM)',
        category: 'women',
        type: 'FRENCH',
        price: 458,
        image: '🌸',
        format: 'spray',
        brand: 'HASSAN IRFAN',
        sizes: {
            '5ML': 458,
            '15ML': 1346,
            '30ML': 3026,
            '50ML': 3880,
            '100ML': 6208,
        }
    },
    {
        id: 29,
        name: 'HASSAN IRFAN SULTAN MUMTAZ        (NEW)',
        category: 'men',
        type: 'ARABIC',
        price: 624,
        image: '🌸',
        format: 'spray',
        brand: 'HASSAN IRFAN',
        sizes: {
            '5ML': 624,
            '15ML': 2230,
            '30ML': 4021,
            '50ML': 5538,
            '100ML': 8860,
        }
    },
    {
        id: 30,
        name: 'HASSAN IRFAN THE SMOKE          (FLAGSHIP)',
        category: 'men',
        type: 'ORIENTAL',
        price: 593,
        image: '🌸',
        format: 'spray',
        brand: 'HASSAN IRFAN',
        sizes: {
            '5ML': 593,
            '15ML': 2066,
            '30ML': 3836,
            '50ML': 5230,
            '100ML': 8368,
        }
    },
    {
        id: 31,
        name: 'HASSAN IRFAN THE SOUL (FLAGSHIP)*****',
        category: 'men',
        type: 'UNIQUE',
        price: 1284,
        image: '🌸',
        format: 'spray',
        brand: 'HASSAN IRFAN',
        sizes: {
            '5ML': 1284,
            '15ML': 3853,
            '30ML': 6104,
            '50ML': 8500,
            '100ML': 12749,
        }
    },
    {
        id: 32,
        name: 'HASSAN IRFAN TROPICAL BLISS***',
        category: 'women',
        type: 'FRENCH',
        price: 499,
        image: '🌸',
        format: 'spray',
        brand: 'HASSAN IRFAN',
        sizes: {
            '5ML': 499,
            '15ML': 1561,
            '30ML': 3268,
            '50ML': 4282,
            '100ML': 6852,
        }
    },
    {
        id: 33,
        name: 'HASSAN IRFAN VETIVER INTENSE*',
        category: 'men',
        type: 'ORIENTAL',
        price: 593,
        image: '🌸',
        format: 'spray',
        brand: 'HASSAN IRFAN',
        sizes: {
            '5ML': 593,
            '15ML': 2066,
            '30ML': 3836,
            '50ML': 5230,
            '100ML': 8368,
        }
    },
    {
        id: 34,
        name: 'AMOUAGE BEACH HUT',
        category: 'unisex',
        type: 'FRENCH',
        price: 804,
        image: '🌹',
        format: 'spray',
        brand: 'AMOUAGE',
        sizes: {
            '10ML': 804,
            '20ML': 1507,
            '30ML': 2913,
            '50ML': 3690,
            '100ML': 5905,
        }
    },
    {
        id: 35,
        name: 'AMOUAGE BELOVED MAN',
        category: 'men',
        type: 'FRENCH',
        price: 1065,
        image: '🌹',
        format: 'spray',
        brand: 'AMOUAGE',
        sizes: {
            '10ML': 1065,
            '20ML': 2029,
            '30ML': 3584,
            '50ML': 4809,
            '100ML': 7694,
        }
    },
    {
        id: 36,
        name: 'AMOUAGE BRACKEN MAN',
        category: 'men',
        type: 'FRENCH',
        price: 986,
        image: '🌹',
        format: 'spray',
        brand: 'AMOUAGE',
        sizes: {
            '10ML': 986,
            '20ML': 1872,
            '30ML': 3382,
            '50ML': 4472,
            '100ML': 7155,
        }
    },
    {
        id: 37,
        name: 'AMOUAGE DIA MEN',
        category: 'men',
        type: 'FRENCH',
        price: 936,
        image: '🌹',
        format: 'spray',
        brand: 'AMOUAGE',
        sizes: {
            '10ML': 936,
            '20ML': 1772,
            '30ML': 3253,
            '50ML': 4258,
            '100ML': 6812,
        }
    },
    {
        id: 38,
        name: 'AMOUAGE EPIC MAN*',
        category: 'men',
        type: 'FRENCH',
        price: 1124,
        image: '🌹',
        format: 'spray',
        brand: 'AMOUAGE',
        sizes: {
            '10ML': 1124,
            '20ML': 2148,
            '30ML': 3737,
            '50ML': 5064,
            '100ML': 8102,
        }
    },
    {
        id: 39,
        name: 'AMOUAGE INTERLUDE',
        category: 'unisex',
        type: 'FRENCH',
        price: 1057,
        image: '🌹',
        format: 'spray',
        brand: 'AMOUAGE',
        sizes: {
            '10ML': 1057,
            '20ML': 2015,
            '30ML': 3565,
            '50ML': 4778,
            '100ML': 7644,
        }
    },
    {
        id: 40,
        name: 'AMOUAGE JOURNEY MAN',
        category: 'men',
        type: 'FRENCH',
        price: 1019,
        image: '🌹',
        format: 'spray',
        brand: 'AMOUAGE',
        sizes: {
            '10ML': 1019,
            '20ML': 1938,
            '30ML': 3467,
            '50ML': 4614,
            '100ML': 7382,
        }
    },
    {
        id: 41,
        name: 'AMOUAGE MEMOIR MAN',
        category: 'men',
        type: 'FRENCH',
        price: 1120,
        image: '🌹',
        format: 'spray',
        brand: 'AMOUAGE',
        sizes: {
            '10ML': 1120,
            '20ML': 2140,
            '30ML': 3726,
            '50ML': 5045,
            '100ML': 8072,
        }
    },
    {
        id: 42,
        name: 'AMOUAGE REFLECTION MAN',
        category: 'men',
        type: 'FRENCH',
        price: 935,
        image: '🌹',
        format: 'spray',
        brand: 'AMOUAGE',
        sizes: {
            '10ML': 935,
            '20ML': 1770,
            '30ML': 3250,
            '50ML': 4252,
            '100ML': 6803,
        }
    },
    {
        id: 43,
        name: 'BVLGARI AZARAN',
        category: 'unisex',
        type: 'FRENCH',
        price: 1793,
        image: '🌹',
        format: 'spray',
        brand: 'BVLGARI',
        sizes: {
            '10ML': 1793,
            '20ML': 3486,
            '30ML': 5456,
            '50ML': 7930,
            '100ML': 12688,
        }
    },
    {
        id: 44,
        name: 'BVLGARI FALKAR *',
        category: 'women',
        type: 'FRENCH',
        price: 1815,
        image: '🌹',
        format: 'spray',
        brand: 'BVLGARI',
        sizes: {
            '10ML': 1815,
            '20ML': 3530,
            '30ML': 5513,
            '50ML': 8025,
            '100ML': 12839,
        }
    },
    {
        id: 45,
        name: 'BVLGARI MAN IN BLACK',
        category: 'men',
        type: 'FRENCH',
        price: 1152,
        image: '🌹',
        format: 'spray',
        brand: 'BVLGARI',
        sizes: {
            '10ML': 1152,
            '20ML': 2204,
            '30ML': 3808,
            '50ML': 5182,
            '100ML': 8292,
        }
    },
    {
        id: 46,
        name: 'BVLGARI ONEKH',
        category: 'unisex',
        type: 'FRENCH',
        price: 955,
        image: '🌹',
        format: 'spray',
        brand: 'BVLGARI',
        sizes: {
            '10ML': 955,
            '20ML': 1810,
            '30ML': 3302,
            '50ML': 4339,
            '100ML': 6943,
        }
    },
    {
        id: 47,
        name: 'BVLGARI TYGAR  *',
        category: 'unisex',
        type: 'FRENCH',
        price: 1135,
        image: '🌹',
        format: 'spray',
        brand: 'BVLGARI',
        sizes: {
            '10ML': 1135,
            '20ML': 2171,
            '30ML': 3765,
            '50ML': 5111,
            '100ML': 8178,
        }
    },
    {
        id: 48,
        name: 'CHANEL BLUE DE CHANNEL-FRENCH ***',
        category: 'unisex',
        type: 'FRENCH',
        price: 809,
        image: '🌹',
        format: 'spray',
        brand: 'CHANEL',
        sizes: {
            '10ML': 809,
            '20ML': 1518,
            '30ML': 2927,
            '50ML': 3714,
            '100ML': 5942,
        }
    },
    {
        id: 49,
        name: 'CHANEL BLUE DE CHANNEL-SWISS ***',
        category: 'unisex',
        type: 'FRENCH',
        price: 1815,
        image: '🌹',
        format: 'spray',
        brand: 'CHANEL',
        sizes: {
            '10ML': 1815,
            '20ML': 3530,
            '30ML': 5513,
            '50ML': 8025,
            '100ML': 12839,
        }
    },
    {
        id: 50,
        name: 'CHANEL BLUE DE CHANNEL - PARFUM  (NEW)',
        category: 'unisex',
        type: 'FRENCH',
        price: 1633,
        image: '🌹',
        format: 'spray',
        brand: 'CHANEL',
        sizes: {
            '10ML': 1633,
            '20ML': 3165,
            '30ML': 5044,
            '50ML': 7243,
            '100ML': 11589,
        }
    },
    {
        id: 51,
        name: 'CHANEL CHANCE EAU TENDRE',
        category: 'unisex',
        type: 'FRENCH',
        price: 825,
        image: '🌹',
        format: 'spray',
        brand: 'CHANEL',
        sizes: {
            '10ML': 825,
            '20ML': 1549,
            '30ML': 2967,
            '50ML': 3780,
            '100ML': 6049,
        }
    },
    {
        id: 52,
        name: 'CHANEL COCO CHANEL',
        category: 'unisex',
        type: 'FRENCH',
        price: 767,
        image: '🌹',
        format: 'spray',
        brand: 'CHANEL',
        sizes: {
            '10ML': 767,
            '20ML': 1434,
            '30ML': 2819,
            '50ML': 3534,
            '100ML': 5654,
        }
    },
    {
        id: 53,
        name: 'CHANEL COCO MADEMOISELLE',
        category: 'men',
        type: 'FRENCH',
        price: 864,
        image: '🌹',
        format: 'spray',
        brand: 'CHANEL',
        sizes: {
            '10ML': 864,
            '20ML': 1628,
            '30ML': 3067,
            '50ML': 3948,
            '100ML': 6318,
        }
    },
    {
        id: 54,
        name: 'CHANEL COCO MADEMOISELLE INTENSE',
        category: 'men',
        type: 'FRENCH',
        price: 820,
        image: '🌹',
        format: 'spray',
        brand: 'CHANEL',
        sizes: {
            '10ML': 820,
            '20ML': 1541,
            '30ML': 2955,
            '50ML': 3761,
            '100ML': 6018,
        }
    },
    {
        id: 55,
        name: 'CHANEL COCO NOIR F',
        category: 'women',
        type: 'FRENCH',
        price: 1028,
        image: '🌹',
        format: 'spray',
        brand: 'CHANEL',
        sizes: {
            '10ML': 1028,
            '20ML': 1956,
            '30ML': 3490,
            '50ML': 4652,
            '100ML': 7443,
        }
    },
    {
        id: 56,
        name: 'CREED AVENTUS*** FRENCH',
        category: 'women',
        type: 'FRENCH',
        price: 848,
        image: '🌹',
        format: 'spray',
        brand: 'CREED',
        sizes: {
            '10ML': 848,
            '20ML': 1596,
            '30ML': 3027,
            '50ML': 3881,
            '100ML': 6210,
        }
    },
    {
        id: 57,
        name: 'CREED AVENTUS*** SPECIAL',
        category: 'unisex',
        type: 'FRENCH',
        price: 1318,
        image: '🌹',
        format: 'spray',
        brand: 'CREED',
        sizes: {
            '10ML': 1318,
            '20ML': 2535,
            '30ML': 4234,
            '50ML': 5893,
            '100ML': 9429,
        }
    },
    {
        id: 58,
        name: 'CREED CREED GOLD',
        category: 'unisex',
        type: 'FRENCH',
        price: 1588,
        image: '🌹',
        format: 'spray',
        brand: 'CREED',
        sizes: {
            '10ML': 1588,
            '20ML': 3077,
            '30ML': 4930,
            '50ML': 7053,
            '100ML': 11286,
        }
    },
    {
        id: 59,
        name: 'CREED GREEN IRISH TWEED',
        category: 'unisex',
        type: 'FRENCH',
        price: 886,
        image: '🌹',
        format: 'spray',
        brand: 'CREED',
        sizes: {
            '10ML': 886,
            '20ML': 1672,
            '30ML': 3124,
            '50ML': 4043,
            '100ML': 6469,
        }
    },
    {
        id: 60,
        name: 'CREED ORIGINAL VETIVER',
        category: 'unisex',
        type: 'FRENCH',
        price: 1760,
        image: '🌹',
        format: 'spray',
        brand: 'CREED',
        sizes: {
            '10ML': 1760,
            '20ML': 3419,
            '30ML': 5371,
            '50ML': 7788,
            '100ML': 12460,
        }
    },
    {
        id: 61,
        name: 'CREED ROYAL OUD',
        category: 'unisex',
        type: 'FRENCH',
        price: 1375,
        image: '🌹',
        format: 'spray',
        brand: 'CREED',
        sizes: {
            '10ML': 1375,
            '20ML': 2650,
            '30ML': 4382,
            '50ML': 6139,
            '100ML': 9823,
        }
    },
    {
        id: 62,
        name: 'CREED SILVER MOUNTAIN WATER*',
        category: 'men',
        type: 'FRENCH',
        price: 788,
        image: '🌹',
        format: 'spray',
        brand: 'CREED',
        sizes: {
            '10ML': 788,
            '20ML': 1476,
            '30ML': 2872,
            '50ML': 3623,
            '100ML': 5796,
        }
    },
    {
        id: 63,
        name: 'CREED SILVER MOUNTAIN WATER - UAE***',
        category: 'men',
        type: 'FRENCH',
        price: 910,
        image: '🌹',
        format: 'spray',
        brand: 'CREED',
        sizes: {
            '10ML': 910,
            '20ML': 1720,
            '30ML': 3185,
            '50ML': 4145,
            '100ML': 6632,
        }
    },
    {
        id: 64,
        name: 'CREED VIRGIN ISLAND WATER    (NEW)',
        category: 'unisex',
        type: 'FRENCH',
        price: 1428,
        image: '🌹',
        format: 'spray',
        brand: 'CREED',
        sizes: {
            '10ML': 1428,
            '20ML': 2756,
            '30ML': 4518,
            '50ML': 6367,
            '100ML': 10187,
        }
    },
    {
        id: 65,
        name: 'DIOR DIOR HOMME',
        category: 'unisex',
        type: 'FRENCH',
        price: 897,
        image: '🌹',
        format: 'spray',
        brand: 'DIOR',
        sizes: {
            '10ML': 897,
            '20ML': 1693,
            '30ML': 3151,
            '50ML': 4088,
            '100ML': 6541,
        }
    },
    {
        id: 66,
        name: 'DIOR FAHRENHEIT***',
        category: 'women',
        type: 'FRENCH',
        price: 1152,
        image: '🌹',
        format: 'spray',
        brand: 'DIOR',
        sizes: {
            '10ML': 1152,
            '20ML': 2204,
            '30ML': 3808,
            '50ML': 5182,
            '100ML': 8292,
        }
    },
    {
        id: 67,
        name: 'DIOR FAHRENHEIT 32',
        category: 'women',
        type: 'FRENCH',
        price: 731,
        image: '🌹',
        format: 'spray',
        brand: 'DIOR',
        sizes: {
            '10ML': 731,
            '20ML': 1361,
            '30ML': 2725,
            '50ML': 3377,
            '100ML': 5404,
        }
    },
    {
        id: 68,
        name: "DIOR J'DORE",
        category: 'unisex',
        type: 'FRENCH',
        price: 816,
        image: '🌹',
        format: 'spray',
        brand: 'DIOR',
        sizes: {
            '10ML': 816,
            '20ML': 1533,
            '30ML': 2945,
            '50ML': 3745,
            '100ML': 5992,
        }
    },
    {
        id: 69,
        name: 'DIOR OUD ISPAHAN  **',
        category: 'unisex',
        type: 'FRENCH',
        price: 963,
        image: '🌹',
        format: 'spray',
        brand: 'DIOR',
        sizes: {
            '10ML': 963,
            '20ML': 1826,
            '30ML': 3322,
            '50ML': 4372,
            '100ML': 6996,
        }
    },
    {
        id: 70,
        name: 'DIOR PURPLE OUD',
        category: 'unisex',
        type: 'FRENCH',
        price: 846,
        image: '🌹',
        format: 'spray',
        brand: 'DIOR',
        sizes: {
            '10ML': 846,
            '20ML': 1591,
            '30ML': 3021,
            '50ML': 3870,
            '100ML': 6193,
        }
    },
    {
        id: 71,
        name: 'DIOR SAUVAGE',
        category: 'unisex',
        type: 'FRENCH',
        price: 799,
        image: '🌹',
        format: 'spray',
        brand: 'DIOR',
        sizes: {
            '10ML': 799,
            '20ML': 1499,
            '30ML': 2901,
            '50ML': 3671,
            '100ML': 5874,
        }
    },
    {
        id: 72,
        name: 'DIOR SAUVAGE ELIXIR',
        category: 'unisex',
        type: 'FRENCH',
        price: 1156,
        image: '🌹',
        format: 'spray',
        brand: 'DIOR',
        sizes: {
            '10ML': 1156,
            '20ML': 2213,
            '30ML': 3819,
            '50ML': 5201,
            '100ML': 8322,
        }
    },
    {
        id: 73,
        name: 'DIOR SAUVAGE UAE    ***',
        category: 'unisex',
        type: 'FRENCH',
        price: 1072,
        image: '🌹',
        format: 'spray',
        brand: 'DIOR',
        sizes: {
            '10ML': 1072,
            '20ML': 2045,
            '30ML': 3603,
            '50ML': 4841,
            '100ML': 7746,
        }
    }
];
